minecraft-server:
  ports:
    - "25565:25565"

  environment:
    EULA: TRUE
    TYPE: FORGE
    FORGEVERSION: 10.13.4.1448

  image: itzg/minecraft-server

  container_name: minecraft-server

  tty: true
  stdin_open: true
  restart: always